//! `wtd ask` — the AI explanation layer over the evidence graph.
//!
//! Division of labor (per intent.md): the deterministic engine discovers and
//! proves; the LLM only explains. This module deterministically selects the
//! evidence relevant to the question, renders it as a bounded text block, and
//! sends it with a grounding system prompt. Every fact the model may state is
//! present verbatim in the evidence block; the prompt forbids anything else.

const std = @import("std");
const types = @import("types.zig");
const engine = @import("engine.zig");
const analysis = @import("analysis.zig");
const ai = @import("ai.zig");

pub const system_prompt =
    \\You are the explanation layer of WhatTheDiff (wtd), a deterministic
    \\semantic diff engine. The engine has already analyzed a corpus of files
    \\and produced the EVIDENCE below. The evidence is the only source of
    \\truth.
    \\
    \\Rules:
    \\1. Never state a fact about the corpus that is not present in the
    \\   evidence. Do not guess file contents, causes, or intent.
    \\2. Cite evidence inline as (path:line) or (path) for every claim.
    \\3. If the evidence is insufficient to answer, say exactly what is
    \\   missing and suggest the wtd command that would surface it.
    \\4. Interpreting evidence is encouraged (e.g. "tls=false on an outlier
    \\   host looks like a misconfiguration worth reviewing") — but label
    \\   interpretation as such.
    \\5. Be concise. Lead with the direct answer, then the supporting
    \\   evidence. Plain prose, no headers.
    \\
    \\Glossary: a "primitive" is one semantic fact extracted from a file
    \\(e.g. a key=value pair). k = how many files contain a primitive,
    \\N = total files. Buckets: universal (k=N), majority (2k>N), minority
    \\(1<k, 2k<=N), unique (k=1). The "consensus core" is all primitives with
    \\2k>N. drift(file) = 1 - Jaccard(file's primitives, core); 0 means pure
    \\consensus, 1 means nothing in common. Outliers are flagged past
    \\mean + 1.5 sigma.
;

const max_focus_artifacts = 4;
const max_listed_artifacts = 30;
const max_unique_per_focus = 25;
const max_missing_per_focus = 25;
const max_canonical_len = 160;

/// Words too generic to identify an artifact.
const stopwords = [_][]const u8{
    "the",      "and",    "why",       "what",  "how",        "is",   "are",   "does",
    "did",      "from",   "with",      "that",  "this",       "file", "files", "than",
    "diff",     "differ", "different", "about", "for",        "who",  "which", "compare",
    "compared", "other",  "others",    "rest",  "everything", "all",
    // bare extensions match every artifact — never useful as focus tokens
     "yaml",  "yml",
    "json",     "md",     "txt",       "conf",  "toml",       "ini",  "cfg",   "env",
};

pub const Options = struct {
    dry_run: bool = false,
    max_tokens: u32 = 4096,
    /// CLI --model override; wins over every env var.
    model: ?[]const u8 = null,
};

/// Deterministically render the evidence block for a question.
pub fn buildEvidence(
    arena: std.mem.Allocator,
    corpus: *const engine.Corpus,
    question: []const u8,
) ![]const u8 {
    const a = &corpus.analysis;
    var out = std.ArrayList(u8).init(arena);
    const w = out.writer();

    try w.print("EVIDENCE (deterministic, generated by the wtd engine)\n\n", .{});
    try w.print(
        "Corpus: {d} artifacts, {d} distinct primitives, {d} observations, {d} skipped files.\n",
        .{ a.n_artifacts, a.n_identities, a.total_observations, corpus.skipped },
    );
    try w.print(
        "Consensus buckets: universal={d} majority={d} minority={d} unique={d}; core={d} primitives.\n",
        .{ a.bucket_counts[0], a.bucket_counts[1], a.bucket_counts[2], a.bucket_counts[3], a.core_size },
    );
    try w.print("Drift: mean={d:.3} stddev={d:.3}.\n\n", .{ a.mean_drift, a.std_drift });

    // Artifact table: all if small; otherwise top-drift plus question matches.
    const order = try sortedByDriftDesc(arena, a.artifact_stats);
    const focus_ids = try matchFocus(arena, corpus, question);

    try w.print("ARTIFACTS (drift, primitives, in-core, unique, outlier):\n", .{});
    var listed: usize = 0;
    for (order) |s| {
        const is_focus = contains(focus_ids, s.id);
        if (listed >= max_listed_artifacts and !is_focus) continue;
        listed += 1;
        try w.print("  {d:.3}  {s}  prims={d} in_core={d} unique={d}{s}\n", .{
            s.drift,
            corpus.artifacts[s.id].path,
            s.total,
            s.in_core,
            s.unique,
            if (s.outlier) "  OUTLIER" else "",
        });
    }
    if (order.len > listed) try w.print("  ... {d} more artifacts omitted (lowest drift)\n", .{order.len - listed});
    try w.print("\n", .{});

    // Factions: groups deviating from consensus together.
    if (corpus.clusters.factions.len > 0) {
        try w.print("FACTIONS (groups sharing the same deviations from consensus):\n", .{});
        for (corpus.clusters.factions, 0..) |f, fi| {
            if (fi >= 6) {
                try w.print("  ... {d} more factions omitted\n", .{corpus.clusters.factions.len - 6});
                break;
            }
            try w.print("  faction of {d} (cohesion {d:.2}): ", .{ f.members.len, f.cohesion });
            const shown_m = @min(f.members.len, 8);
            for (f.members[0..shown_m], 0..) |m, i| {
                if (i > 0) try w.print(", ", .{});
                try w.print("{s}", .{corpus.artifacts[m].path});
            }
            if (f.members.len > shown_m) try w.print(" (+{d} more)", .{f.members.len - shown_m});
            try w.print("\n", .{});
            for (f.signature[0..@min(f.signature.len, 5)]) |sig| {
                try w.print("    shared deviation: {s} {s} ({d}/{d} members)\n", .{
                    @tagName(sig.kind), clip(sig.canonical), sig.present, f.members.len,
                });
            }
        }
        try w.print("\n", .{});
    }

    // Focus detail: question-matched artifacts, else flagged outliers,
    // else the single highest-drift artifact.
    var focus = focus_ids;
    if (focus.len == 0) {
        var fallback = std.ArrayList(u32).init(arena);
        for (order) |s| {
            if (s.outlier and fallback.items.len < max_focus_artifacts) try fallback.append(s.id);
        }
        if (fallback.items.len == 0 and order.len > 0 and a.n_artifacts > 1) {
            try fallback.append(order[0].id);
        }
        focus = fallback.items;
    }

    for (focus) |fid| try writeFocus(arena, w, corpus, fid);

    return out.items;
}

fn writeFocus(
    arena: std.mem.Allocator,
    w: anytype,
    corpus: *const engine.Corpus,
    fid: u32,
) !void {
    const a = &corpus.analysis;
    const art = corpus.artifacts[fid];
    const stat = a.artifact_stats[fid];

    try w.print("FOCUS {s} (drift={d:.3}, {d} primitives, {d} in core, {d} unique{s})\n", .{
        art.path,     stat.drift,  stat.total,
        stat.in_core, stat.unique, if (stat.outlier) ", OUTLIER" else "",
    });

    // Membership bitset for this artifact (sets hold dense store indexes).
    var member = try std.DynamicBitSet.initEmpty(arena, corpus.store.count());
    for (corpus.sets[fid]) |idx| member.set(idx);

    // Unique primitives (present only in this artifact), with line numbers.
    var shown: usize = 0;
    for (0..corpus.store.count()) |i| {
        const obs = corpus.store.at(i);
        if (obs.distinct_artifacts != 1 or a.n_artifacts < 2) continue;
        const occ = obs.occurrences.items[0];
        if (occ.artifact != fid) continue;
        if (shown == 0) try w.print("  unique to this file:\n", .{});
        shown += 1;
        if (shown > max_unique_per_focus) continue;
        if (occ.line > 0) {
            try w.print("    {s} {s} (line {d})\n", .{ @tagName(obs.kind), clip(obs.canonical), occ.line });
        } else {
            try w.print("    {s} {s}\n", .{ @tagName(obs.kind), clip(obs.canonical) });
        }
    }
    if (shown > max_unique_per_focus) try w.print("    ... {d} more unique primitives omitted\n", .{shown - max_unique_per_focus});

    // Consensus-core primitives this artifact is missing.
    var missing: usize = 0;
    for (0..corpus.store.count()) |i| {
        const obs = corpus.store.at(i);
        if (2 * @as(usize, obs.distinct_artifacts) <= a.n_artifacts) continue;
        if (member.isSet(i)) continue;
        if (missing == 0) try w.print("  in the consensus core but MISSING from this file:\n", .{});
        missing += 1;
        if (missing > max_missing_per_focus) continue;
        try w.print("    {s} {s} (in {d}/{d} files)\n", .{
            @tagName(obs.kind), clip(obs.canonical), obs.distinct_artifacts, a.n_artifacts,
        });
    }
    if (missing > max_missing_per_focus) try w.print("    ... {d} more missing core primitives omitted\n", .{missing - max_missing_per_focus});
    if (shown == 0 and missing == 0) try w.print("  matches the consensus core exactly.\n", .{});
    try w.print("\n", .{});
}

/// Match question tokens against artifact paths (case-insensitive substring).
fn matchFocus(
    arena: std.mem.Allocator,
    corpus: *const engine.Corpus,
    question: []const u8,
) ![]u32 {
    var out = std.ArrayList(u32).init(arena);

    // Dots stay inside tokens so "rogue.yaml" matches only that file;
    // edge punctuation (sentence-final dots etc.) is trimmed afterwards.
    const q_lower = try std.ascii.allocLowerString(arena, question);
    var tokens = std.mem.tokenizeAny(u8, q_lower, " \t\n\r?!,;:'\"()[]{}");

    var wanted = std.ArrayList([]const u8).init(arena);
    outer: while (tokens.next()) |raw| {
        const tok = std.mem.trim(u8, raw, ".");
        if (tok.len < 3) continue;
        for (stopwords) |sw| {
            if (std.mem.eql(u8, tok, sw)) continue :outer;
        }
        try wanted.append(tok);
    }

    for (corpus.artifacts) |art| {
        if (out.items.len >= max_focus_artifacts) break;
        const path_lower = try std.ascii.allocLowerString(arena, art.path);
        for (wanted.items) |tok| {
            if (std.mem.indexOf(u8, path_lower, tok) != null) {
                try out.append(art.id);
                break;
            }
        }
    }
    return out.items;
}

fn sortedByDriftDesc(arena: std.mem.Allocator, stats: []const analysis.ArtifactStat) ![]analysis.ArtifactStat {
    const copy = try arena.dupe(analysis.ArtifactStat, stats);
    std.mem.sort(analysis.ArtifactStat, copy, {}, struct {
        fn lessThan(_: void, x: analysis.ArtifactStat, y: analysis.ArtifactStat) bool {
            if (x.drift != y.drift) return x.drift > y.drift;
            return x.id < y.id;
        }
    }.lessThan);
    return copy;
}

fn contains(ids: []const u32, id: u32) bool {
    for (ids) |x| {
        if (x == id) return true;
    }
    return false;
}

fn clip(s: []const u8) []const u8 {
    if (s.len <= max_canonical_len) return s;
    var end: usize = max_canonical_len;
    while (end > 0 and (s[end] & 0xC0) == 0x80) end -= 1;
    return s[0..end];
}

/// Run the full ask flow: build evidence, call the model, print the answer.
pub fn run(
    arena: std.mem.Allocator,
    corpus: *const engine.Corpus,
    question: []const u8,
    opts: Options,
) !u8 {
    const evidence = try buildEvidence(arena, corpus, question);
    const user_prompt = try std.mem.concat(arena, u8, &.{
        evidence, "\nQUESTION: ", question, "\n",
    });

    const stdout = std.io.getStdOut().writer();

    if (opts.dry_run) {
        try stdout.print("--- system ---\n{s}\n\n--- user ---\n{s}", .{ system_prompt, user_prompt });
        return 0;
    }

    var cfg = (try ai.detect(arena)) orelse {
        try std.io.getStdErr().writer().writeAll(
            \\wtd: no AI provider configured.
            \\  set ANTHROPIC_API_KEY (Anthropic Messages API), or
            \\  set OPENROUTER_API_KEY (OpenAI-compatible; OPENROUTER_BASE_URL/OPENROUTER_MODEL honored)
            \\  optional overrides: WTD_AI_MODEL, WTD_AI_URL
            \\  or run with --dry-run to inspect the prompt without a key.
            \\
        );
        return 2;
    };

    if (opts.model) |m| cfg.model = m;

    try std.io.getStdErr().writer().print(
        "wtd: asking {s} ({d} artifacts of evidence)...\n",
        .{ cfg.model, corpus.artifacts.len },
    );

    const answer = ai.complete(arena, cfg, system_prompt, user_prompt, opts.max_tokens) catch {
        return 1;
    };

    try stdout.print("{s}\n", .{answer});
    return 0;
}

// -------------------------------------------------------------- tests -----

const evidence_mod = @import("evidence.zig");

fn testCorpus(arena: std.mem.Allocator) !engine.Corpus {
    // 3 conformers + 1 rogue, built directly (no fs).
    var store = evidence_mod.Store.init(arena);
    var sets = std.ArrayList([]u32).init(arena);
    var artifacts = std.ArrayList(types.Artifact).init(arena);

    const shared = [_][]const u8{ "host=db", "port=5432", "tls=true" };
    const rogue = [_][]const u8{ "host=db", "backdoor=on", "debug=1" };

    const names = [_][]const u8{ "configs/a.yaml", "configs/b.yaml", "configs/c.yaml", "configs/rogue.yaml" };
    for (names, 0..) |name, aid| {
        var set = std.ArrayList(u32).init(arena);
        const prims: []const []const u8 = if (aid == 3) &rogue else &shared;
        for (prims, 0..) |c, line| {
            const r = try store.add(@intCast(aid), .{
                .kind = .kv,
                .canonical = c,
                .line = @intCast(line + 1),
            });
            if (r.first_for_artifact) try set.append(r.index);
        }
        try artifacts.append(.{ .id = @intCast(aid), .path = name, .kind = .yaml, .size = 100 });
        try sets.append(try set.toOwnedSlice());
    }

    const result = try analysis.analyze(arena, &store, 4, sets.items);
    const owned_sets = try sets.toOwnedSlice();
    const clusters = try @import("cluster.zig").detect(arena, &store, &result, owned_sets);
    return .{
        .artifacts = try artifacts.toOwnedSlice(),
        .store = store,
        .sets = owned_sets,
        .analysis = result,
        .clusters = clusters,
        .skipped = 0,
    };
}

test "evidence focuses on the artifact named in the question" {
    var arena_state = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena_state.deinit();
    const arena = arena_state.allocator();

    const corpus = try testCorpus(arena);
    const ev = try buildEvidence(arena, &corpus, "why is rogue.yaml different?");

    try std.testing.expect(std.mem.indexOf(u8, ev, "FOCUS configs/rogue.yaml") != null);
    try std.testing.expect(std.mem.indexOf(u8, ev, "backdoor=on") != null);
    try std.testing.expect(std.mem.indexOf(u8, ev, "MISSING from this file") != null);
    try std.testing.expect(std.mem.indexOf(u8, ev, "port=5432") != null);
    // Conformers are not focus sections.
    try std.testing.expect(std.mem.indexOf(u8, ev, "FOCUS configs/a.yaml") == null);
}

test "evidence falls back to outliers when no artifact is named" {
    var arena_state = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena_state.deinit();
    const arena = arena_state.allocator();

    const corpus = try testCorpus(arena);
    const ev = try buildEvidence(arena, &corpus, "what stands out here?");

    try std.testing.expect(std.mem.indexOf(u8, ev, "FOCUS configs/rogue.yaml") != null);
}

test "evidence building is deterministic" {
    var arena_state = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena_state.deinit();
    const arena = arena_state.allocator();

    const corpus = try testCorpus(arena);
    const e1 = try buildEvidence(arena, &corpus, "why is rogue.yaml different?");
    const e2 = try buildEvidence(arena, &corpus, "why is rogue.yaml different?");
    try std.testing.expectEqualStrings(e1, e2);
}
